### ISSUE TITLE
[Feat] Provide a bulk translation workflow for all Strings in a file

### ISSUE THREAD

**Issue by lukemmtt** [FlineDev/RemafoX#18]
## Problem Statement

Let's say I have a view controller with 30 unlocalized strings that you want to localize. This is a common situation for (a) indie devs localizing their apps for the first time, or (b) small dev teams who prefer to have one person responsible for localizing the app (like me).

With Bartycrouch, my workflow was really efficient and looked like this:

1. Select the unlocalized string
2. Use a custom Automator "Localize String" script via keyboard shortcut to replace string with Bartycrouch.translate template text in-line
3. Repeat for all strings (not building / running build script yet)
4. Find & replace "key" entries to save time (i.e. for the format class.element.piece, might replace all instances of "class" with "paywall")
5. Make any additional "key" changes
6. Finally, build project, which executes the build script and replaces all instances with Enums in one shot

With ReMafoX, my workflow is much more tedious:

1. Select the unlocalized string
2. Hit ReMafoX keyboard shortcut
3. Manually enter translation key, trying to remain consistent with the other 29 keys in the file
4. Hit "Insert as String"  (and hope that I entered the key appropriately, if not, navigate manually to the Localizable.strings file to fix)
5. Proceed to next string, hit ReMafoX keyboard shortcut
6. Enter translation key again from scratch (Can't copy & paste existing key, since ReMafoX replaces the clipboard text with the complete Enum created in step 4.)
7. Repeat another 28 times

## Suggested Solution

There are a few different options here:

- Add functionality within the "Add Translation" dialog box for contextual awareness for the translation key component. Examples of this could be: (a) Auto-populating the last key that was entered, (b) Suggesting a key "class" based on the name of the Swift file, etc
- Ideally, create a new bulk workflow dialog box that will allow rapid conversion of all unlocalized strings in a file to ReMafoX enums

## Additional Considerations

I recognize that the "preferred workflow" might be to have each dev on my team localize things as they go with ReMafoX, but I don't yet have enough consistency across my dev teammates to make that a superior option vs handling all localizations myself.

Similarly, if you're thinking "if bartycrouch works for you, keep using bartycrouch"—I'm here because Bartycrouch is still broken for me in Xcode 14 (https://github.com/FlineDev/BartyCrouch/issues/201), and I love the idea of ReMafoX in general.

Related: https://github.com/FlineDev/ReMafoX/issues/8#issuecomment-1255139253

Keep up the good work!

**Comment by Jeehut** [comment]
@lukemmtt Thank you very much for the detailed feature request, it's much appreciated! ❤️ 

I totally wasn't aware that BartyCrouch could be used the way you described above, if I had been, I would have made sure to cover this use case in ReMafoX from the beginning. That's a really cool process, saving a lot of time!

I love the idea of adding a bulk workflow dialog box and I think that's how I want to tackle this right away. The contextual awareness thing is also a cool idea I already have planned, but not based on the Swift file (an Xcode extension technically can't even see that), instead by providing auto-completion based on already existing keys in the same Strings file which should also help save a lot of time. I just created the related feature in https://github.com/FlineDev/ReMafoX/issues/22, make sure to add your vote (👍 ) so I can prioritize it accordingly.

So let's focus this request on the "bulk translation workflow". As this seems to be a process already available in BartyCrouch and because I want ReMafoX to be superior to BartyCrouch (for obvious reasons), I think this has relatively high priority and might even be implemented within the scope of the first October feature update.

Again, thank you for reporting! 👏

**Comment by Jeehut** [comment]
This feature is no longer necessary as Xcode 15 provides an improved editor and automatic key extraction capabilities with String Catalogs. Read [my FAQ](https://www.fline.dev/the-missing-string-catalogs-faq-for-xcode-15/) for more details.

Anyone interested, please migrate to String Catalogs and give it a chance. If you still find struggles there, let me know!
