### ISSUE TITLE
[Use] Text Block Count does not seem to work with Extensions

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [FlineDev/ReMafoX#24]
## Steps to Reproduce:

I have an app with an Apple Watch extension. For simplicity I just share the the same translations between the extension and the main app. All in all I have 239 entries in my .strings file. (I can see that in my previous translation tool). 
I tested ReMaFox in the Beta and directly went for the Pro Tier. Now the app prompts me to upgrade to the Max plan since it discovered 735 entries. Since my app is made from 3 parts: iOS App, watchOS app, Siri extension it just counts up all the text blocks even though they are equal. 

1. Create an app with multiple extensions
2. Copy the Localized.strings file to each extension
3. Use ReMaFox and see how it multiplies the number of text blocks times the number of extensions 

## Expected Behavior:

Equal Text Blocks in multiple extension should counted multiple times. Otherwise I would need a new ReMaFox project for each extension. 

## Current Behavior:
ReMaFox counts for the text blocks in each extension again. 

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 12.6 (Build 21G115)
- System CPU: Apple M1 Pro

</details>

**Comment by Sn0wfreezeDev** [comment]
I could definitely try the shared folder I thought that Xcode requires a certain folder structure here. So that every localized file is in a sub-folder of the target that uses it. 

I have a small utility that does the updating for me using my current localization system. So it would be one step less for me if the Shared folder works 😊

**Comment by Jeehut** [comment]
@Sn0wfreezeDev Yes it is totally possible to only have one Strings file and link the same file to multiple targets. From the compilers perspective, it's exactly the same thing as you currently have because each target has its own copy build phase and each target will get its own copy. But _you_ only have to maintain one file.

For your convenience, I prepared a demo project with multiple targets and a shared folder:
https://github.com/Jeehut/SharedLocalizableDemo

I also recorded this GIF while setting it up, showing you the relevant part of creating a shared folder and linking it properly:
![SharedLocalizableDemo](https://user-images.githubusercontent.com/6942160/195873816-29843556-67af-4926-9d1c-3af728cfee02.gif)

If this resolves your problem, feel free to close the issue as well. If you have another use case where the current counting doesn't work for you, please comment that below so I can adjust things accordingly.

I hope this helps!

**Comment by Jeehut** [comment]
@Sn0wfreezeDev
Have you had the chance to try the shared folder approach yet? If you have any issues with it, please let me know!

**Comment by Sn0wfreezeDev** [comment]
I haven't had the chance yet, but I will try it tomorrow. I had to work on different projects before.

**Comment by Sn0wfreezeDev** [comment]
I tried it today and migrated to only one Localizable.strings file shared between all extensions. 
This solved the issue and I'm down to around 220 text blocks. Thanks for the support 👍 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/3126229/198222453-9141bd5d-1dc4-486c-9659-f64a1b9b30be.png">

**Comment by Jeehut** [comment]
@Sn0wfreezeDev Great to hear! Glad that I could help.

If you come across anything else, please don't hesitate to create another issue.
