### ISSUE TITLE
[Feat] Add Support for Welsh language

### ISSUE THREAD

**Issue by Sherlouk** [FlineDev/ReMafoX#32]
## Steps to Reproduce:

1. Setup ReMafoX with a project which supports English (development language) and additionally Welsh
1. See that when you try to add a localisation that Welsh is not displayed

## Expected Behavior:

Welsh should listed in the UI with a text field allowing me to provide a suitable translation.

## Current Behavior:

Welsh is not displayed an option to provide translations for.

![image](https://user-images.githubusercontent.com/15193942/195983605-2efe089d-7b78-47bb-abc2-2323ae0970f6.png)
![image](https://user-images.githubusercontent.com/15193942/195983609-5266dde0-fbb3-4fc5-a5df-edbec69eea9b.png)

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 13.0 (Build 22A5342f)
- System CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

</details>

**Comment by Sherlouk** [comment]
After discussing this with you on Twitter, I've converted this to a feature request. I understand that at present ReMafoX has prioritised and added support for the default system languages which Apple lists [here](https://www.apple.com/ios/feature-availability/#system-language-system-language) which doesn't include Welsh.

This is a high priority feature for me though personally 🙁  I understand for most it's not though.

**Comment by Jeehut** [comment]
For anyone else coming across this, I want to first mention that I created [this FAQ](https://github.com/FlineDev/ReMafoX/discussions/38) page explaining exactly the current language limits.

Having that said, please note that the main reason I have not included all languages yet is because for the smart pluralization feature to work properly, I have to integrate the correct mapping per language from [this table](https://www.unicode.org/cldr/cldr-aux/charts/34/supplemental/language_plural_rules.html) into ReMafoX and thus adding a language takes a bit of time and therefore I went with 40 for version 1.0.

That doesn't mean though, that adding a single language is a huge deal for me. And as you're one of my first paying customers and you reported a whole set of bugs & feature requests, I will make sure to give Welsh a special treatment and add it in the next update already. I think this is well deserved. Thank you for all your input!

**Comment by Jeehut** [comment]
@Sherlouk Do you need "Welsh" (`cy`) or "Welsh (United Kingdom)" (`cy-GB`)? There seem to be 2 options in Xcode.
I'm guessing that "Welsh" (`cy`) will do, no?

**Comment by Jeehut** [comment]
@Sherlouk I just added support for "Welsh" (`cy`) and it will be included with the next update (`1.0.3`) very soon.

**Comment by Sherlouk** [comment]
Awesome! Can't wait - thanks for the rapid responses. Yeah `cy` is fine and what we use!

**Comment by Jeehut** [comment]
Just uploaded and submitted version `1.0.3` with the fix for review. Should be available in ~24 h from now.
