### ISSUE TITLE
[Bug] Only generates enum from stringsdict file and does not consider strings

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [FlineDev/ReMafoX#60]
## Steps to Reproduce:

When I have a project that contains `.stringsdict` files for plurals and `.strings` files, ReMaFox seems to select randomly, which it uses to base its enum file generation on. 
I was not able to get it back to working after I added an new string (which was placed correctly in the strings file), but then ReMaFox removed all content of the enum and replaced it with the content from the `.stringsdict` file. 
ReMaFox definitely finds all resources since it shows them in the preview and selector when adding a new string. 

1. Create a project that uses `.strings` and `.stringsdict` files 
1. Initialize ReMaFox
1. ReMaFox mit work as expected, but might also generate the enum based only on the `.stringsdict` file

## Expected Behavior:

Generate the enum based on all string resources in the whole project. 

## Current Behavior:

ReMaFox might base the enum file only on `.stringsdict` files. 

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.1.1 (Build 55)
- System Version: 13.0 (Build 22A379)
- System CPU: Apple M1 Pro
- Tier: Pro

</details>

**Comment by Sn0wfreezeDev** [comment]
I updated to 1.1.1 and it seems to work now. I don't know if this is just temporary or a permanent fix. If you worked on this you can definitely close the issue 😊

**Comment by Jeehut** [comment]
@Sn0wfreezeDev Thank you for reporting this issue.

I did not experience what you have reported here yet, so there's no dedicated fix for it shipped with `1.1.1`. But I changed the logic for the sources that are relevant for the generated Swift file as part of a fix for https://github.com/FlineDev/ReMafoX/issues/49, so that might have solved this here as well.

I'll close this one as it seems to be fixed, if you run into it ever again, I'd need a sample project which you can easily create using the trick explained [here](https://github.com/FlineDev/ReMafoX/issues/25#issuecomment-1279713546), to keep your project file structure but not upload any _actual_ file contents except for the files you want to provide them for (Strings(dict) and `.remafox` files). Feel free to send it to the email address in the 'Help' menu.

But I hope it's not needed anymore! 🙏
