### ISSUE TITLE
[Bug] Invalid redeclaration of enum case

### ISSUE THREAD

**Issue by stephent** [FlineDev/ReMafoX#78]
## Steps to Reproduce:

Add the following to the source language strings file and generate the enum file:

```
"Delete account" = "Delete account";

"Delete account…" = "Delete account…";
```

## Expected Behavior:

On building, there should be no error. The Enum file should distinguish between the two strings shown above as they're not identical cases.

## Current Behavior:

```
    /// 🇬🇧 English (United Kingdom): "Delete account"
    public static var deleteAccount: String {
        Bundle.module.localizedString(forKey: "Delete account", value: nil, table: "Localizable")
    }

    /// 🇬🇧 English (United Kingdom): "Delete account…"
    public static var deleteAccount: String {
        Bundle.module.localizedString(forKey: "Delete account…", value: nil, table: "Localizable")
    }
```

Results in `../Sources/AccountServicesUI/Sources/RemafoX.swift:1635:23 Invalid redeclaration of 'deleteAccount'`

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.4.0 (Build 62)
- System Version: 12.6.2 (Build 21G320)
- System CPU: Apple M1 Pro
- Tier: Free

</details>

**Comment by Jeehut** [comment]
@stephent Thank you for reporting this issue.

As you've probably guessed already, RemafoX currently deletes special characters from keys when generating the related code to make the code read nicely and conform to Swift naming conventions. But your example shows a valid use case where ellipsis (…) should be kept somehow, so I just added special handling for them in RemafoX. Instead of the above "Current behavior" code you posted, in the future RemafoX will produce this code instead:

```Swift
    /// 🇬🇧 English (United Kingdom): "Delete account"
    public static var deleteAccount: String {
        Bundle.module.localizedString(forKey: "Delete account", value: nil, table: "Localizable")
    }

    /// 🇬🇧 English (United Kingdom): "Delete account…"
    public static var deleteAccountEllipsis: String {
        Bundle.module.localizedString(forKey: "Delete account…", value: nil, table: "Localizable")
    }
```

I will finalize the release of `1.4.1` now, it should be available within the next 24 hours.

Having this said, I also want to mention that issues like this can be prevented entirely by using semantic keys, like the ones I suggest in my [Best Practices video](https://to.remafox.app/workflow). But I can understand that there are situations where you can't simply change the key naming conventions of your team or project.

I hope this helps!

**Comment by stephent** [comment]
Thanks for the super quick fix @Jeehut 👍

(Semantic keys: agreed. It's on the to do list, but it's a legacy code base and will take a little time to get fully cleaned up.)
