### ISSUE TITLE
[Feat] Add (force) override translation option when encountering a key that already exists

### ISSUE THREAD

**Issue by NickAtGit** [FlineDev/ReMafoX#81]
## Problem Statement

I had a translation that was fine for a moment but later I decided to change the text. So I wanted to override the existing translations. So I tried to delete the key and the translation in my `en` strings file and then I typed in my new string in the file where I wanted it. When I hit then `Translate` button in RemafoX I got an error message telling me, that the key already exists.

## Suggested Solution

When showing me the error message provide a force override option that ignores the warning and does what I want. Ideally I just want to copy my key out of my strings file. Start RemafoX, tell it the key and my new text, hit translate, force override, insert, done.

## Additional Considerations

---

**Comment by Jeehut** [comment]
@NickAtGit Thank you for requesting this feature.

I think it makes a lot of sense to give the developer more flexibility in how to deal with situations like this. I hadn't thought about your use case and simply wanted to prevent duplicate keys, but of course in some situations a developer might be trying to override a key on purpose. I will think about a solution that tackles your use case.

**Comment by Jeehut** [comment]
@NickAtGit I just reworked how the Add Translation window handles existing keys. Starting with `1.5.0` to be released in a couple of days, instead of just failing with an error when an existing key is entered and an insert is attempted, the new behavior will look like this:
![Bildschirmfoto 2023-04-15 um 02 20 52](https://user-images.githubusercontent.com/6942160/232173709-aaa0ca71-d3f8-4c86-a0b3-f00b22d0a811.png)

This gives developers full flexibility as to what they want to achieve:
1. Instead of a failure, they will get a warning which is less invasive but still prevents duplicate keys.
1. Users can press "Insert Existing Key" if they want to just reuse the existing key but let RemafoX do the insertion.
1. Users can also opt for ignoring the warning and providing new translation values which will override the existing key.

This should cover your use case as well as https://github.com/FlineDev/RemafoX/issues/95. I hope you like it!

Thanks again for the feature request. It helped make Remafox better for everyone! 🎉
