### ISSUE TITLE
[Bug] [Code: PRAxE] Re-configuring an already configured project fails

### ISSUE THREAD

**Issue by ConfusedVorlon** [FlineDev/ReMafoX#92]
## Steps to Reproduce:

1. delete project (trying to fix but)
2. recreate it

## Expected Behavior:

any error should be helpful...

## Current Behavior:

<img width="991" alt="Screenshot 2023-04-03 at 10 55 54" src="https://user-images.githubusercontent.com/586910/229476545-8dd90d4d-1a7b-4fac-ab4a-64b1393ce37f.png">

what do I 'double–press' ??

## Environment

PRAxE

<details>
<summary>Show environment details</summary>

- App Version: 1.4.1 (Build 63)
- System Version: 13.2.1 (Build 22D68)
- System CPU: Apple M1 Ultra
- Tier: Pro

</details>

**Comment by ConfusedVorlon** [comment]
<img width="1012" alt="Screenshot 2023-04-03 at 10 57 15" src="https://user-images.githubusercontent.com/586910/229476840-27649ddc-af27-4de9-b2da-aa537ed9c938.png">

clicking file a bug report, then close leaves the app in this state (it never completes)

**Comment by ConfusedVorlon** [comment]
it seems like there should be a 'continue using this file' option

**Comment by Jeehut** [comment]
@ConfusedVorlon Thank you for reporting this. There are several things I want to point out here:

1. The error you see should only appear if you're trying to setup a project that was already previously set up. RemafoX detects this by seeing that there already is a configuration file ending with `.remafox`. If you had multiple `.remafox` files in one project, it might be confusing, thus you see this error to prevent such a situation.

2. To answer your question "what do I 'double–press'?": Double-press the config file at the path RemafoX is showing you int he error, so it would be the `Chatter.remafox` file. Maybe the error isn't clear enough, so I will consider re-wording it to clarify that you should be double-pressing the config file in the Finder app. Is it clear now?

3. As for the navigation issue you reported via "clicking file a bug report, then close leaves the app in this state (it never completes)": There are actually several such issues in different places and they are all partly due to some lacking features in SwiftUI window management and partly due to me not being proficient in `AppKit`. But I've just [reworked the architecture](https://www.fline.dev/migrating-to-tca-1-0/?source=github.com) of the RemafoX app which should help fix some of these issues. And I will further improve the navigation of the app and write tests for all kinds of situations so these kind of issues shouldn't happen in the future. So, I'm working on it.

4. As for "it seems like there should be a 'continue using this file' option": If I understand you correctly, what you mean here is that when the app detects the initial error you've come across, there should be a button to automatically do what the "double-press the config file" would do. And I think that you're totally right there, it would improve the UX significantly if this was the case. So I will try to provide that, even though there are other things (like navigation issues) that I need to tackle first.

I've been busy with traveling and relocating since October last year, so I couldn't tackle bigger tasks. But I'm now back in full swing, so you can expect significant improvements to RemafoX in the coming months ahead. Thank you for your patience and for all the bug reports & feature requests! 👍

**Comment by ConfusedVorlon** [comment]
re 2, I did figure this out eventually, but it is confusing. When you say 'double press', I assume you mean something in the existing UI.
If you need me to quit this flow and open something in the finder, you should say so.

Also - I'd say 'open in finder', or 'double-click in finder' rather than double press.

4) yes - you know what I want to do, you are able to do it - why not at least offer to do it!

**Comment by Jeehut** [comment]
@ConfusedVorlon I just fixed all issues mentioned in this thread, so I'm closing this. The fixes will be shipped as part of the next release `1.5.0` in a couple of days. Thanks again for reporting, digging into fixing more bugs now! 🐞 🔨 

Here's what it will look like when users try to configure an already configured project in the future:
![Bildschirmfoto 2023-04-12 um 02 01 42](https://user-images.githubusercontent.com/6942160/231313735-2f1e515e-cd78-482d-b80a-81480949af93.png)
