### ISSUE TITLE
[Feat] If a string exists, just offer to use it

### ISSUE THREAD

**Issue by ConfusedVorlon** [FlineDev/ReMafoX#95]
## Problem Statement

I tried to replace "cancel" with a translation
I reach for `Alert.Cancel `(which is my standard approach)
Remafox warned me that this string exists - but doesn't let me use it

## Suggested Solution

Show the string, and offer to insert it

Show me that the value is the same, and insert `Loc.Alert.Cancel.string` if I click to 'Use This'

**Comment by Jeehut** [comment]
@ConfusedVorlon Thank you for reporting this. This is a great small daily-life improving enhancement and I'll tackle it soon!

**Comment by Jeehut** [comment]
@ConfusedVorlon  I just reworked how the Add Translation window handles existing keys. Starting with `1.5.0` to be released in a couple of days, instead of just failing with an error when an existing key is entered and an insert is attempted, the new behavior will look like this:
![Bildschirmfoto 2023-04-15 um 02 20 52](https://user-images.githubusercontent.com/6942160/232173709-aaa0ca71-d3f8-4c86-a0b3-f00b22d0a811.png)

This gives developers full flexibility as to what they want to achieve:
1. Instead of a failure, they will get a warning which is less invasive but still prevents duplicate keys.
1. Users can press "Insert Existing Key" if they want to just reuse the existing key but let RemafoX do the insertion.
1. Users can also opt for ignoring the warning and providing new translation values which will override the existing key.

This should cover your use case as well as https://github.com/FlineDev/RemafoX/issues/81. I hope you like it!

Thanks again for the feature request. It helped make Remafox better for everyone! 🎉
