### ISSUE TITLE
[Improvement] You don't need to ask for folder permission every time a project is added

### ISSUE THREAD

**Issue by ConfusedVorlon** [FlineDev/ReMafoX#96]
## Problem Statement

Currently, I can only have one project in the Remafox setup, so I need to remove the project and click on the .remafox file of another project to open that.
This triggers the project setup UI. The only purpose of this seems to be getting permission to access the folder.
You shouldn't need to do this every time - once is enough!

## Suggested Solution

Fortunately - I created a package which makes this all really easy. It stores your access and lets you quickly check whether you have access to a given folder
https://github.com/ConfusedVorlon/SwiftySandboxFileAccess

## Additional Considerations

less of an issue when the 'only one project' bug is fixed, but still - why would you ask file permission if you already have it...

**Comment by Jeehut** [comment]
@ConfusedVorlon Thank you for the suggestion and the library, I'll check it out.

Indeed, not having to do this is gonna make this less of a problem, so I will focus on that first. But the library looks interesting nevertheless, I'll give it a try.

**Comment by Jeehut** [comment]
Well, actually having thought about this I think I will keep the current behavior, because when a user removes a project from RemafoX and I keep the permission around, I'm not following the minimum permission principles Apple designed these APIs by. I shouldn't keep around access to a folder if I don't have a reason to do that.

The more important topic is to fix the "only one project" bug as you mentioned. I'm on it right now. Closing this.
