### ISSUE TITLE
[Feat] Option to Retranslate if I change my base string

### ISSUE THREAD

**Issue by ConfusedVorlon** [FlineDev/ReMafoX#98]
## Problem Statement

Let's say I have a screen with a title

Loc.Screen.Title = "Welcome to my app"

I then change my string

Loc.Screen.Title = "Getting started guide"

Remafox won't offer to re-translate this string as it has already translated it

## Suggested Solution

options:
1 detect change of the base string and offer to retranslate
(Translate Empty & Changed strings becomes the standard button)
2 allow me to enter the key in the remafox interface somewhere 'retranslate these keys...'
3 let me signal my desire with a comment

//RETRANSLATE
"Input.Message" = "Ask Me Anything";

## Additional Considerations

I'm not sure what the best interface option is here.
Currently, I just delete a key and insert a new one, but that seems messy...

I think #1 would be my preferred option...

**Comment by Jeehut** [comment]
@ConfusedVorlon Thank you for requesting this feature!

When you're talking about "retranslate", do you mean when the translation key has already been added to a project and you want to change the translation afterwards? Or do you mean while in the Add Translation window, you type a source text, hit translate, then change the source text?

In the latter case, it's on purpose that no warning is shown, because in fact what I sometimes is this:
1. I enter a Source translation using clear, simple terminology so the translated text is more correct
2. I hit translate
3. Then I adjust the Source translation, making it shorter or sound more fancy (but less clear for machine translation)
4. Then I hit Insert

But if you're requesting the first, changing a translation after it has been added to a project:
I think that https://github.com/FlineDev/RemafoX/issues/12 might be exactly what you want, make sure to upvote it. Also, feel free to add any details if the text you see doesn't cover your exact use case.

I'm closing this as a duplicate unless you bring up reasons why this is a separate feature, then I'll reopen.

**Comment by ConfusedVorlon** [comment]
I think we're talking at cross purposes.
This is the case I'm thinking of

1) On Monday, I insert a string which is the title for Screen1
Key is `Screen1.Title`
Value is "_This is Screen 1_"

I do machine translation, all is good

2) On Wednesday, I decide that I don't like the title I chose, so I want to change the text

Key is still `Screen1.Title` (this is still the title for Screen 1 after all)
However, now, the value is "_Welcome to Screen 1, Have a nice day_"

The way I change the value is by editing the .strings file in the en_GB folder
That's easy enough - but now that I'm using a new title, I want Remafox to retranslate Italian, Greek, Etc

At the moment, the only way I can achieve that is by manually deleting the key in every language that isn't English, and then clicking 'Translate Empty'*

What I want is to just click 'Translate Changed'


* I could click 'retranslate all' - but that would be excessive

**Comment by ConfusedVorlon** [comment]
I don't think this is a duplicate of the strings editor request...

**Comment by Jeehut** [comment]
@ConfusedVorlon Ok, now it's clear what you're trying to achieve, thank you for the additional detail.

What I don't understand is how the Strings Editor isn't helping. What you say above is that you "change the value by editing the .strings file", which is exactly what you will be able to do with a Strings Editor. And, of course, the Strings Editor will also include a button to machine translate a specific key. Maybe it's not mentioned in the thread (feel free to add this requirement as a comment), but I certainly plan to add such a button. Wouldn't that solve your use case?

> At the moment, the only way I can achieve that is by manually deleting the key in every language that isn't English, and then clicking 'Translate Empty'*

There's actually no need to delete a key from all other languages manually. You can make use of the `normalize` feature [as described here](https://github.com/FlineDev/RemafoX/discussions/77#discussioncomment-5016971) to delete the key and just add it back to the Source language afterwards and build again, to "change" your localizations. Should be faster.

**Comment by ConfusedVorlon** [comment]
sure - if you have a 'retranslate this key' functionality in the editor, that does the job. I didn't spot that in the thread.

**Comment by Jeehut** [comment]
@ConfusedVorlon
You're right, it wasn't mentioned, sorry for the confusion. I just added [a comment](https://github.com/FlineDev/RemafoX/issues/12#issuecomment-1510509200) there to make it more clear. 🎉
